version: '3'
services:
    app:
        build: .
        container_name: igame-app
        volumes:
            - ./:/var/www
        networks:
            - igame-network
        env_file:
            - .env

    nginx:
        image: nginx:alpine
        container_name: igame-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - igame-network

    db:
        platform: linux/x86_64
        image: mysql:5.6.47
        container_name: igame-db
        ports:
            - "3306:3306"
        volumes:
            - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf
            - ./etc/database/auth.sql:/docker-entrypoint-initdb.d/auth.sql
        networks:
            - igame-network
        env_file:
            - .env

networks:
    igame-network:
        driver: bridge